//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Venta_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Venta_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
      
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    

#line default
#line hidden

#line 3 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                                                                                __o = Url.Action("PartialViewSearch");


#line default
#line hidden

#line 4 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
        if (Model != null)
    {
        

#line default
#line hidden

#line 5 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                foreach (var venta in Model)
                {
                

#line default
#line hidden

#line 6 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                   __o = venta.Nombre;


#line default
#line hidden

#line 7 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                   __o = venta.Preciocosto;


#line default
#line hidden

#line 8 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                    __o = venta.Preciocosto * 1;


#line default
#line hidden

#line 9 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                        using (Html.BeginForm("RemoveFromCart", "Venta", FormMethod.Post))
                            {
                        

#line default
#line hidden

#line 10 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                   __o = Html.Hidden("id_producto", venta.Id);


#line default
#line hidden

#line 11 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                                             
                        

#line default
#line hidden

#line 12 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                 
                            }

#line default
#line hidden

#line 13 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                     
                }

#line default
#line hidden

#line 14 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                

        

#line default
#line hidden

#line 15 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                __o = ViewBag.TotalAmount;


#line default
#line hidden

#line 16 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                                              

        

#line default
#line hidden

#line 17 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
            __o = Url.Action("Checkout", "Cart");


#line default
#line hidden

#line 18 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                                                                             
    }
    else
    {
        

#line default
#line hidden

#line 19 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                                                             

        

#line default
#line hidden

#line 20 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                                                                                            
    }

#line default
#line hidden
DefineSection("scripts", () => {

});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";


#line default
#line hidden

#line 3 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
    if (Model != null)
    {
    

#line default
#line hidden

#line 4 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
            foreach (var venta in Model)
                {
            

#line default
#line hidden

#line 5 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
               __o = venta.nombre;


#line default
#line hidden

#line 6 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
               __o = venta.Preciocostoline default
#line hidden

#line 7 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                __o = venta.costo * Preciocosto

#line default
#line hidden

#line 8 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                    using (Html.BeginForm("RemoveFromCart", "Cart", FVentaethod.Post))
                            {
                    

#line default
#line hidden

#line 9 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
               __o = Html.Hidden("id_producto", venta.id_produId#line default
#line hidden

#line 10 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                                                                  
                    

#line default
#line hidden

#line 11 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                             
                            }

#line default
#line hidden

#line 12 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
                 
                }

#line default
#line hidden

#line 13 "C:\Users\Francisco Huchin\AppData\Local\Temp\AD525BE84FFEE4801A077FB8C43225CB2338\4\RefaccionariaFrontend\RefaccionariaFrontend\Views\Venta\Index.cshtml"
            
    }

    <h3 class="text-end">Total: $@ViewBag.TotalAmount</h3>

        <a href="@Url.Action("Checkout", "Cart")" class="btn btn-primary">Realizar compra</a>

#lin
    else
    {
        <p class="text-center">No hay productos en el carrito de compras.</p>

        <i class="bi bi-cart3 d-flex justify-content-center" style="font-size: 124px; color: lightgrey"></i>
    }e default
#line hidden
}
}
}
