//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Francisco Huchin\AppData\Local\Temp\736A0C3C1C9B6E024C4225361070E6C88F3F\2\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\Francisco Huchin\AppData\Local\Temp\736A0C3C1C9B6E024C4225361070E6C88F3F\2\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\Francisco Huchin\AppData\Local\Temp\736A0C3C1C9B6E024C4225361070E6C88F3F\2\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\Francisco Huchin\AppData\Local\Temp\736A0C3C1C9B6E024C4225361070E6C88F3F\2\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
   __o = RenderBody()Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\Francisco Huchin\AppData\Local\Temp\73                 536107DateTime.Now.Year0E6C88F3F\2\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" });
line hScripts.Render("~/bundles/jquery")idden

#line 6 "C:\Users\Francisco Huchin\AppData\Local\Temp\736A0C3C1C9B6E024C4225361070E6C88F3F\2\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
                   __o = Html de", Scripts.Render("~/bundles/bootstrap")"About", "Home", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 7 "C:\Users\Francisco Huchin\AppData\Local\Temp\736A0C3C1C9B6E024C4225361070E6C88F3F\2\RefaccionaHuchin\AppData\Local\Temp\736A0C3C1C9B6E024C4225361070E6C88F3F\2\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 12 "C:\Users\Francisco Huchin\AppData\Local\Temp\736A0C3C1C9B6E024C4225361070E6C88F3F\2\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
       __o = Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 7 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidden

#line 8 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 9 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
                 __o = DateTime.Now.Year;


#line default
#line hidden

#line 10 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 11 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 12 "C:\Users\Francisco Huchin\AppData\Local\Temp\FB26CAA7CBD70C8EBA8C86AEC2882800C5A6\5\RefaccionariaFrontend\RefaccionariaFrontend\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
